# Site settings
title: Skoude's Blog
email: skoude@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technology blog focused mainly on Cloud, IAAS, Ansible, Java, Docker and Vaadin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.skoude.com" # the base hostname & protocol for your site
twitter_username: KariSkytta
github_username:  skoude

# Build settings
markdown: kramdown
